# Docker Compose for development and production
version: "3.8"

services:
  weblisk:
    build: .
    ports:
      - "3000:3000"
    environment:
      - WEBLISK_ENV=production
      - WEBLISK_LOG_LEVEL=INFO
      - WEBLISK_LOG_FORMAT=json
      - WEBLISK_HOSTNAME=0.0.0.0
      - WEBLISK_PORT=3000
    healthcheck:
      test: [
        "CMD",
        "deno",
        "eval",
        "fetch('http://localhost:3000/health').then(r => r.ok ? Deno.exit(0) : Deno.exit(1))",
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - weblisk-network

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - weblisk-network
    profiles:
      - monitoring

  # Optional: Add log aggregation with Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - weblisk-network
    profiles:
      - monitoring

networks:
  weblisk-network:
    driver: bridge
