# Prometheus monitoring configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "weblisk_rules.yml"

scrape_configs:
  - job_name: "weblisk"
    static_configs:
      - targets: ["weblisk:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: "weblisk-health"
    static_configs:
      - targets: ["weblisk:3000"]
    metrics_path: "/health"
    scrape_interval: 15s
    scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
